### ISSUE TITLE
Make `class` optional in the config file

### ISSUE THREAD

**Issue by missmatsuko** [clubstudioltd/craft-inline-svg#2]
I get an error if I don't have `class` in my config file. I don't want to add any classes, but I need to put an item with an empty value in the config file.

```
PHP Notice – yii\base\ErrorException
Undefined index: class

in my-site/vendor/clubstudioltd/craft-inline-svg/src/services/InlineSvg.php

/**
 * Renders a list of classes to be applied to the generated SVG.
 *
 * @param  string $class
 * @return string
 */
protected function renderClasses($class)
{
    return trim(sprintf('%s %s', $this->config['class'], $class));
}
```

**Comment by missmatsuko** [comment]
Actually, maybe the whole config file can be optional? Just default to no classes and passing the absolute url like Craft's `svg()`?

**Comment by scottwakefield** [comment]
Hey @missmatsuko,

Thanks for reporting this. I'll get things updated so that the configuration can be optional without things breaking.

Leave it with me 👍

**Comment by scottwakefield** [comment]
Hey @missmatsuko,

I've just published a [new release](https://github.com/clubstudioltd/craft-inline-svg/releases/tag/v0.1.2) that loads the plugin configuration from the settings model instead of directly from the local configuration file. This should mean that the local config file is no longer required. 

I hope that helps!
